---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: "rows"
    theme: "readable"
    fig_width: 11
    fig_height: 8.5
    fig_mobile: FALSE
knit: (function(inputFile, encoding){ 
    out_dir <- '../';
    rmarkdown::render(inputFile, encoding = encoding, output_file=file.path(dirname(inputFile), out_dir, 'flexdashboard')) 
  })
---

```{r, include=FALSE, warning=F, message=F}
# knit options
knitr::opts_chunk$set(
  echo = TRUE
  , warning = FALSE
  , message = FALSE
  , results='hide'
  , fig.width = 10
  , fig.height = 8
  , include = F # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!INCLUDE OFF SO NOT PRINTED WITH FLEXDASHBOARD
)
# bread-and-butter
library(tidyverse)
library(lubridate)
library(viridis)
library(scales)
library(latex2exp)
# visualization
library(kableExtra)
library(cowplot)
library(RColorBrewer)
library(ggpubr) #creating and customizing ggplot2-based publication ready plots
library(mapview) #Interactive maps
library(leafpop) #map html popup
library(tidytext) # reorder within facets
library(ggtext) # color text in ggplot
# spatial analysis
library(sf)
library(lwgeom)
library(ggmap) # nice ggplot maps
library(terra)
# set seed
set.seed(11)
```

```{r, results='hide'}
# turn off the s2 processing 
## https://stackoverflow.com/questions/68478179/how-to-resolve-spherical-geometry-failures-when-joining-spatial-data
sf::sf_use_s2(FALSE)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE, include=FALSE}
remove(list = ls())
gc()
```

```{r wcs-ls-dta, results='hide'}
# load data
wf_landscapes <- sf::read_sf("../data/Wildfire_Crisis_Strategy_Landscapes/Wildfire_Crisis_Strategy_Landscapes_(Feature_Layer).shp") %>% 
  dplyr::rename_with(tolower) %>% 
  sf::st_make_valid() %>% 
  dplyr::mutate(
    hectares = (as.numeric(sf::st_area(geometry))/10000) 
    , Mil.Hectares = hectares %>% 
      scales::comma(suffix = " M", scale = 1e-6, accuracy = .01)
    , acres = (as.numeric(sf::st_area(geometry))/4046.85642) 
    , Mil.Acres = acres %>% 
      scales::comma(suffix = " M", scale = 1e-6, accuracy = .01)
  ) %>% 
  dplyr::left_join(
    data.frame(state = datasets::state.name, state_abb = datasets::state.abb)
    , by = join_by("state")
  ) %>% 
  dplyr::mutate(
    area_name = paste0(
      ifelse(is.na(state_abb) | state_abb == "", "UNK", state_abb)
      , ": "
      , name
    )
  )
  # manual label placement
  # dplyr::left_join(
  #   readr::read_csv("../data/wildfirepriority_WCS202308/area_label_placement.csv")
  #   , by = dplyr::join_by("area_name")
  # )
#rename sf geom column
  names(wf_landscapes)[names(wf_landscapes)==tolower(attr(wf_landscapes, "sf_column"))] = "geometry"
  sf::st_geometry(wf_landscapes) = "geometry"
# set crs
  transform_crs <- sf::st_crs(wf_landscapes)
# view
  wf_landscapes %>% dplyr::glimpse()
```

```{r ls-cnstrnt-dta, results='hide'}
# load landscape constraint scenario data
constrained_by_scnro_ls <-
  list.files("../data/wildfirepriority_WCS202308/landscapes/",pattern = "\\.csv$") %>%
  purrr::keep(stringr::str_starts(.,"wfpriority_all_sc")) %>% 
  purrr::map(function(x){
    readr::read_csv(
      paste0("../data/wildfirepriority_WCS202308/landscapes/",x)
      , name_repair = "universal"
      , col_types = cols(.default = "c")
    ) %>% 
    dplyr::rename_with(tolower) %>% 
    dplyr::rename_with(make.names) %>% 
    dplyr::select(state,name,tidyselect::ends_with("_m2"),tidyselect::starts_with("pct_")) %>% 
    dplyr::mutate(scenario_id = stringr::word(x,3,sep="_") %>% readr::parse_number()) %>% 
    dplyr::relocate(scenario_id)
  }) %>%
  dplyr::bind_rows() %>%
  dplyr::inner_join(
    wf_landscapes %>%
      sf::st_drop_geometry() %>%
      dplyr::select(state,name,area_name)
    , by = dplyr::join_by(state,name)
  ) %>%
  dplyr::relocate(area_name,.after = "scenario_id") %>%
  dplyr::group_by(area_name,scenario_id) %>%
  dplyr::filter(dplyr::row_number()==1) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    dplyr::across(
      tidyselect::ends_with("_m2")
      , ~ as.numeric(.x) / 10000
    )
    , dplyr::across(
      tidyselect::starts_with("pct_")
      , ~ as.numeric(.x)
    )
  ) %>%
  dplyr::rename_with(
    ~ gsub("_m2", "_ha", .x)
    , tidyselect::ends_with("_m2")
  ) %>%
  # calculate pct reduction
  dplyr::mutate(
    pct_rdctn1_protected = -1*(1 - pct_rmn1_protected)
    , pct_rdctn2_slope = -1*(pct_rmn1_protected - pct_rmn2_slope)
    , pct_rdctn3_roads = -1*(pct_rmn2_slope - pct_rmn3_roads)
    , pct_rdctn4_riparian = -1*(pct_rmn3_roads - pct_rmn4_riparian)
    , pct_rdctn5_administrative = -1*(pct_rmn4_riparian - pct_rmn5_administrative)
    , pct_rdctn_total = -1*(1 - pct_rmn5_administrative)
    , pct_covertype_area = covertype_area_ha/feature_area_ha
    # scenario description
    , scenario_lab = factor(
      scenario_id
      , levels = 1:3
      , labels = paste0("Scenario ", 1:3)
      , ordered = T
    ) %>% forcats::fct_rev()
    , scenario_desc = factor(
      scenario_id
      , levels = 1:3
      , labels = c("Scenario 1\n(status quo)", "Scenario 2\n(slopes+roads)", "Scenario 3\n(slopes+roads+admin)")
      , ordered = T
    )
  )
```

```{r, warning=FALSE, message=FALSE, echo=FALSE, include=FALSE}
remove(list = ls()[grep("_temp",ls())])
gc()
```

```{r fshed-spatial}
### fireshed spatial data
fireshed <- sf::st_read("../data/firesheds/Fireshed_Registry3A_Fireshed/Fireshed_Registry%3A_Fireshed_(Feature_Layer).shp") %>%
  sf::st_transform(transform_crs) %>% 
  setNames(c(
      "shape_id"
      , "area_ha"
      , "fireshed_id"
      , "fireshed_name"
      , "fireshed_code"
      , "fireshed_state"
      , "nopas"
      , "objectid"
      , "fshed_id"
      , "exp_total"
      , "exp_usfs"
      , "exp_nonfs"
      , "exp_usfs_protected"
      , "exp_nonfs_protected"
      , "exp_usfs_managed"
      , "exp_nonfs_managed"
      , "exp_usfs_forest"
      , "exp_nonfs_forest"
      , "exp_usfs_nonforest"
      , "exp_nonfs_nonforest"
      , "exp_usfs_conifer"
      , "exp_nonfs_conifer"
      , "exp_usfs_managedforest"
      , "exp_nonfs_managedforest"
      , "exp_usfs_managedconifer"
      , "exp_nonfs_managedconifer"
      , "exp_nonfs_nonconifer_hihaz"
      , "dist_vs"
      , "crisis_strategy"
      , "key_preformance_indicator"
      , "national_usfs_rank"
      , "national_all_land_rank"
      , "regional_usfs_rank"
      , "regional_all_land_rank"
      , "start_date"
      , "end_date"
      , "geometry"
  )) %>% 
  dplyr::mutate(
    exposure_pct_rank = dplyr::percent_rank(exp_total)
    , exposure_pct_rank_grp = dplyr::case_when(
      exposure_pct_rank >= 1-0.01 ~ "Top 1%"
      , exposure_pct_rank >= 1-0.05 ~ "Top 5%"
      , exposure_pct_rank >= 1-0.10 ~ "Top 10%"
      , exposure_pct_rank >= 1-0.25 ~ "Top 25%"
      , TRUE ~ "Bottom 75%"
    ) %>% 
    factor(
      levels = c("Top 1%","Top 5%","Top 10%","Top 25%","Bottom 75%")
      , ordered = T
    )
    # there is also a national_all_land_rank column
    , ntllandrank_pct_rank = dplyr::percent_rank(-national_all_land_rank)
    , ntllandrank_pct_rank_grp = dplyr::case_when(
        ntllandrank_pct_rank >= 1-0.01 ~ "Top 1%"
        , ntllandrank_pct_rank >= 1-0.05 ~ "Top 5%"
        , ntllandrank_pct_rank >= 1-0.10 ~ "Top 10%"
        , ntllandrank_pct_rank >= 1-0.25 ~ "Top 25%"
        , TRUE ~ "Bottom 75%"
      ) %>% 
      factor(
        levels = c("Top 1%","Top 5%","Top 10%","Top 25%","Bottom 75%")
        , ordered = T
      )
    , crisis_strategy = ifelse(is.na(crisis_strategy),"Not High Risk",crisis_strategy) %>% 
      as.factor() %>% 
      forcats::fct_shift()
  )
  #rename sf geom column
    names(fireshed)[names(fireshed)==tolower(attr(fireshed, "sf_column"))] = "geometry"
    sf::st_geometry(fireshed) = "geometry"
    # calculate area
    fireshed <- fireshed %>% 
      dplyr::mutate(
        fireshed_area_ha = as.numeric(sf::st_area(geometry))/10000
        , fireshed_area_acres = (fireshed_area_ha*10000)/4046.85642
      )
## fireshed_proj_area spatial data
fireshed_proj_area <- sf::st_read("../data/firesheds/Fireshed_Registry3A_Project_Area/Fireshed_Registry%3A_Project_Area_(Feature_Layer).shp") %>%
  sf::st_transform(transform_crs) %>% 
  setNames(c(
      "shape_id"
      , "fireshed_id"
      , "pa_id"
      , "pa_area_ha"
      , "objectid"
      , "pa_id2"
      , "fshed_id"
      , "exp_total"
      , "exp_usfs"
      , "exp_nonfs"
      , "exp_usfs_protected"
      , "exp_nonfs_protected"
      , "exp_usfs_managed"
      , "exp_nonfs_managed"
      , "exp_usfs_forest"
      , "exp_nonfs_forest"
      , "exp_usfs_nonforest"
      , "exp_nonfs_nonforest"
      , "exp_usfs_conifer"
      , "exp_nonfs_conifer"
      , "exp_usfs_managedforest"
      , "exp_nonfs_managedforest"
      , "exp_usfs_managedconifer"
      , "exp_nonfs_managedconifer"
      , "exp_nonfs_nonconifer_hihaz"
      , "dist_vs"
      , "pctrecentlydisturbed"
      , "start_date"
      , "end_date"
      , "geometry"
  )) %>% 
  dplyr::mutate(
    exposure_pct_rank = dplyr::percent_rank(exp_total)
    , exposure_pct_rank_grp = dplyr::case_when(
      exposure_pct_rank >= 1-0.01 ~ "Top 1%"
      , exposure_pct_rank >= 1-0.05 ~ "Top 5%"
      , exposure_pct_rank >= 1-0.10 ~ "Top 10%"
      , exposure_pct_rank >= 1-0.25 ~ "Top 25%"
      , TRUE ~ "Bottom 75%"
    ) %>% 
    factor(
      levels = c("Top 1%","Top 5%","Top 10%","Top 25%","Bottom 75%")
      , ordered = T
    )
  )
  #rename sf geom column
    names(fireshed_proj_area)[names(fireshed_proj_area)==tolower(attr(fireshed_proj_area, "sf_column"))] = "geometry"
    sf::st_geometry(fireshed_proj_area) = "geometry"
    # calculate area
    fireshed_proj_area <- fireshed_proj_area %>% 
      dplyr::mutate(
        pa_area_ha = as.numeric(sf::st_area(geometry))/10000
        , pa_area_acres = (pa_area_ha*10000)/4046.85642
      ) %>% 
      # JOIN WITH FIRESHED DATA
      dplyr::inner_join(
        fireshed %>%
          sf::st_drop_geometry() %>%
          dplyr::select(fireshed_id, crisis_strategy, exp_total
                        , exposure_pct_rank, exposure_pct_rank_grp
          ) %>% 
          dplyr::rename(exposure_total=exp_total) %>% 
          dplyr::rename_with(
            ~ paste0("fireshed_",.x)
            , -c(fireshed_id)
          )
        , by = dplyr::join_by(fireshed_id)
      ) %>%
      dplyr::select(pa_id,pa_area_ha
                    ,exp_total,exposure_pct_rank,exposure_pct_rank_grp
                    , tidyselect::starts_with("fireshed_")
      ) %>% 
      dplyr::rename(exposure_total=exp_total) %>%
      dplyr::rename_with(
        ~ paste0("pa_", .x, recycle0 = TRUE)
        , tidyselect::starts_with("exp")
      )
```


```{r fs-ld-dta}
# load fireshed constraint scenario data
constrained_by_scnro_ls_pa <-
  list.files("../data/wildfirepriority_WCS202308/fireshed/",pattern = "\\.csv$") %>%
  purrr::keep(stringr::str_starts(.,"wfpriority_fireshed_sc")) %>% 
  purrr::map(function(x){
    readr::read_csv(
      paste0("../data/wildfirepriority_WCS202308/fireshed/",x)
      , name_repair = "universal"
      , col_types = cols(.default = "c")
    ) %>% 
    dplyr::rename_with(tolower) %>% 
    dplyr::rename_with(make.names) %>% 
    dplyr::select(state,name,pa_id,tidyselect::ends_with("_m2"),tidyselect::starts_with("pct_")) %>% 
    dplyr::mutate(scenario_id = stringr::word(x,3,sep="_") %>% readr::parse_number()) %>% 
    dplyr::relocate(scenario_id)
  }) %>%
  dplyr::bind_rows() %>%
  dplyr::inner_join(
    wf_landscapes %>%
      sf::st_drop_geometry() %>%
      dplyr::select(state,name,area_name)
    , by = dplyr::join_by(state,name)
  ) %>%
  dplyr::relocate(area_name,.after = "scenario_id") %>%
  dplyr::mutate(
    dplyr::across(
      tidyselect::ends_with("_m2")
      , ~ as.numeric(.x) / 10000
    )
    , dplyr::across(
      tidyselect::starts_with("pct_")
      , ~ as.numeric(.x)
    )
  ) %>%
  dplyr::rename_with(
    ~ gsub("_m2", "_ha", .x)
    , tidyselect::ends_with("_m2")
  ) %>%
  dplyr::group_by(area_name,pa_id,scenario_id) %>%
  dplyr::arrange(desc(pct_pa_intrsct)) %>%
  dplyr::filter(dplyr::row_number()==1) %>%
  dplyr::ungroup() %>%
  dplyr::filter(pct_pa_intrsct>=0.00001) %>%
  # calculate pct reduction
  dplyr::mutate(
    pct_rdctn1_protected = -1*(1 - pct_rmn1_protected)
    , pct_rdctn2_slope = -1*(pct_rmn1_protected - pct_rmn2_slope)
    , pct_rdctn3_roads = -1*(pct_rmn2_slope - pct_rmn3_roads)
    , pct_rdctn4_riparian = -1*(pct_rmn3_roads - pct_rmn4_riparian)
    , pct_rdctn5_administrative = -1*(pct_rmn4_riparian - pct_rmn5_administrative)
    , pct_rdctn_total = -1*(1 - pct_rmn5_administrative)
    , pct_covertype_area = covertype_area_ha/feature_area_ha
    # calculate level of constraint
      , cnstrnt_lvl = dplyr::case_when(
          -pct_rdctn_total > 0.8 ~ 1
          , -pct_rdctn_total >= 0.6 ~ 2
          , -pct_rdctn_total >= 0.0 ~ 3
        )
      , cnstrnt_class = factor(
          cnstrnt_lvl 
          , levels = 1:3
          , labels = c("high constraint", "med. constraint", "low constraint")
          , ordered = T
        ) %>% forcats::fct_rev()
      , rmn_cnstrnt_class = factor(
          cnstrnt_lvl 
          , levels = 1:3
          , labels = c("0–19% treatable", "20–40% treatable", ">40% treatable")
          , ordered = T
        ) %>% forcats::fct_rev()
      # scenario description
      , scenario_lab = factor(
          scenario_id
          , levels = 1:3
          , labels = paste0("Scenario ", 1:3)
          , ordered = T
        ) %>% forcats::fct_rev()
      , scenario_desc = factor(
        scenario_id
        , levels = 1:3
        , labels = c("Scenario 1\n(status quo)", "Scenario 2\n(slopes+roads)", "Scenario 3\n(slopes+roads+admin)")
        , ordered = T
      )
  ) %>% 
  # join with fireshed data
  dplyr::inner_join(
    fireshed_proj_area %>%
      sf::st_drop_geometry() %>%
      dplyr::select(pa_id, tidyselect::starts_with("pa_exposure"), tidyselect::starts_with("fireshed_")) %>%
      dplyr::mutate(pa_id=as.character(pa_id))
    , by = dplyr::join_by(pa_id)
  )
```

```{r, warning=FALSE, message=FALSE, echo=FALSE, include=FALSE}
remove(list = ls()[grep("_temp",ls())])
gc()
```

```{r stamen-basemap-fn}
#########################################################################
#########################################################################
# global vars to work with functions below
#########################################################################
#########################################################################
# set crs for working with ggmap
plt_crs <- 3857
# list of area names to work over
area_nm_list <- sort(unique(constrained_by_scnro_ls$area_name))
# color palette for fill of f.p.a.'s
cols_rdylbu_lt <- c(
  "low constraint" = rev(RColorBrewer::brewer.pal(n=3,name="RdYlBu"))[1]
  , "med. constraint" = rev(RColorBrewer::brewer.pal(n=3,name="RdYlBu"))[2]
  , "high constraint" = rev(RColorBrewer::brewer.pal(n=3,name="RdYlBu"))[3]
)
# function to highlight largest patch with fireshed project areas under
cols_rdylbu_dk <- c(
  "low constraint" = rev(RColorBrewer::brewer.pal(n=11,name="RdYlBu"))[2]
  , "med. constraint" = rev(RColorBrewer::brewer.pal(n=11,name="RdYlBu"))[7]
  , "high constraint" = rev(RColorBrewer::brewer.pal(n=11,name="RdYlBu"))[10]
)
#########################################################################
#########################################################################
# Make each plot individually by landscape as solution to small multiples
# this block defines function
#########################################################################
##################hack to align plots for ggmap
ggmap_bbox_fn <- function(map, my_crs=3857) {
    if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
    # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
    # and set the names to what sf::st_bbox expects:
    map_bbox <- setNames(unlist(attr(map, "bb")), c("ymin", "xmin", "ymax", "xmax"))
    # Convert the bbox to an sf polygon, transform it to 3857, 
    # and convert back to a bbox (convoluted, but it works)
    bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), my_crs))
    # Overwrite the bbox of the ggmap object with the transformed coordinates 
    attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
    attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
    attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
    attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
    map
}
#########################################################################
#########################################################################
#########################################################################

# function to plot basemap
landscape_basemap_fn <- function(row_n=1) {
  # buffer for smaller areas
  if_smaller_ha_temp <- wf_landscapes %>% 
    dplyr::pull(hectares) %>% 
    quantile(0.45) %>% 
    purrr::pluck(1)
  # should zoom in?
  zoom_level <- dplyr::case_when(
    area_nm_list[row_n] %in% c(
      "WA: Colville Northeast Washington Vision"
      , "CA: Southern California Fireshed Risk Reduction Strategy"
      ) ~ 7
    , area_nm_list[row_n] %in% c(
      "UT: Wasatch"
      , "CA: Trinity Forest Health and Fire-Resilient Rural Communities"
      , "ID: Nez Perce-Clearwater-Lower Salmon"
      , "NV: Sierra and Elko Fronts"
      , "OR: Mount Hood Forest Health and Fire-Resilient Communities"
    ) ~ 8
    , area_nm_list[row_n] %in% c(
      "CA: Plumas Community Protection"
      , "CA: North Yuba"
      , "MT: Kootenai Complex"
      , "UT: Pine Valley"
    ) ~ 9
    , 
      (wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
        ) %>% 
        dplyr::pull(hectares) %>% 
        purrr::pluck(1)
        <= if_smaller_ha_temp
      ) ~ 10
    , TRUE ~ 8
  )
  # should buffer extend?
  buffer_box <- dplyr::case_when(
    area_nm_list[row_n] %in% c("WA: Colville Northeast Washington Vision") ~ 50000
    , area_nm_list[row_n] %in% c(
      "CA: Southern California Fireshed Risk Reduction Strategy"
      , "ID: Nez Perce-Clearwater-Lower Salmon"
      , "MT: Kootenai Complex"
    ) ~ 40000
    , area_nm_list[row_n] %in% c(
      "AZ: San Carlos Apache Tribal Forest Protection"
      , "NV: Sierra and Elko Fronts"
      , "UT: Pine Valley"
    ) ~ 21000
    , area_nm_list[row_n] %in% c(
      "CA: Plumas Community Protection"
      , "CA: North Yuba"
      , "CA: Trinity Forest Health and Fire-Resilient Rural Communities"
      , "OR: Mount Hood Forest Health and Fire-Resilient Communities"
    ) ~ 35000
    , area_nm_list[row_n] %in% c("UT: Wasatch") ~ 5000
    , 
      (wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
        ) %>% 
        dplyr::pull(hectares) %>% 
        purrr::pluck(1)
        <= if_smaller_ha_temp
      ) ~ 15000
    , TRUE ~ 5000
  )
  
  # bounding box
  bb_temp <- 
    # use extent of fireshed project areas
    fireshed_proj_area %>% 
    dplyr::select(pa_id, geometry) %>% 
    dplyr::mutate(pa_id=as.character(pa_id)) %>% 
    dplyr::inner_join(
      constrained_by_scnro_ls_pa %>% 
        dplyr::filter(
          area_name == area_nm_list[row_n]
          & pct_pa_intrsct>=0.25
        )
      , by = dplyr::join_by("pa_id")
      , multiple = "first"
    ) %>% 
    sf::st_union() %>% 
    sf::st_transform(crs=5070) %>% 
    sf::st_buffer(as.numeric(buffer_box)) %>% 
    sf::st_transform(crs=4326) %>% # same as get_map return
    sf::st_bbox()
  # set bbox for get call
  bbox_temp <- c(
    bottom = bb_temp[[2]]
    , top = bb_temp[[4]]
    , right = bb_temp[[3]]
    , left = bb_temp[[1]]
  )
  # get map
  hey_ggmap <- ggmap::get_stamenmap(
    bbox = bbox_temp
    , zoom = zoom_level
    , maptype = "terrain" #"toner-hybrid" # "terrain"
    , crop = T
  )
  # ggmap(hey_ggmap)
  # apply align function
    hey_ggmap_aligned <- ggmap_bbox_fn(hey_ggmap, plt_crs) # Use the function
  # plot
  plt <- ggmap(hey_ggmap_aligned) + 
    # geom_sf(
    #   data = wf_landscapes %>% 
    #     dplyr::filter(
    #         area_name == area_nm_list[row_n]
    #       ) %>% 
    #     sf::st_transform(crs=plt_crs)
    #   , fill = NA, color = "black", lwd = 0.3
    #   , inherit.aes = F
    # ) +
    coord_sf(
      expand = FALSE
    ) +
    labs(
      title = "" #area_nm_list[row_n]
    ) +
    theme_light() +
    theme(
      legend.position =  "top"
      , legend.direction = "horizontal"
      , legend.title = element_text(size = 9, face = "bold")
      , legend.text = element_text(size = 9)
      , legend.margin = margin(c(0,0,-10,0))
      , plot.title = element_text(size = 10, face = "bold") #, hjust = 0.5
      , strip.text = element_text(size = 10, color = "black", face = "bold")
      , axis.title = element_blank()
      , axis.text = element_blank()
      , axis.ticks = element_blank()
      , panel.grid = element_blank()
      , plot.margin = margin(0, 0, 0, 0, "cm")
      , plot.caption = element_text(size = 9, color = "black", hjust = 0, vjust = 3)
    )
  # return
  return(plt)
}
# landscape_basemap_fn(row_n = 2)
###### set plot basemap in global function
# uncomment for testing
plt_basemap <- NULL
# plt_basemap <- landscape_basemap_fn(row_n = 4)
```

```{r spatial-frmwrk-map-fn}
# function to plot basemap + spatial framework
spatial_frmwrk_map_fn <- function(row_n = 1) {
  # join fireshed project area data to spatial data
  fireshed_proj_area_dta_temp <- fireshed_proj_area %>% 
    dplyr::select(pa_id, geometry) %>% 
    dplyr::mutate(pa_id=as.character(pa_id)) %>% 
    dplyr::inner_join(
      constrained_by_scnro_ls_pa %>% 
        dplyr::filter(
          area_name == area_nm_list[row_n]
          & pct_pa_intrsct>=0.25
        )
      , by = dplyr::join_by("pa_id")
      , multiple = "first"
    ) 
  # aggregate for note
  sum_dta_temp <- fireshed_proj_area_dta_temp %>% 
    sf::st_drop_geometry() %>% 
    dplyr::filter(fireshed_crisis_strategy %in% c("USFS-Only", "All-Lands")) %>% 
    dplyr::summarise(total_area_ha = sum(feature_area_ha)) %>% 
    dplyr::mutate(total_area_acres = (total_area_ha*10000)/4046.85642) %>% 
    dplyr::mutate(
      dplyr::across(
        tidyselect::starts_with("total_area")
        , ~ scales::comma(.x, suffix = "k", scale = 1e-3, accuracy = 1)
      )
    )
  # plot
  plt <- plt_basemap +
    geom_sf(data = fireshed_proj_area_dta_temp %>% 
        sf::st_transform(crs=plt_crs)
      , aes(fill = fireshed_crisis_strategy, color = "Project Area\nboundary")
      , alpha = 0.8
      , lwd = 1.3
      , inherit.aes = F
    ) +
    geom_sf(
      data = fireshed %>%
        sf::st_filter(
          wf_landscapes %>%
            dplyr::filter(area_name == area_nm_list[row_n]) %>% 
            dplyr::select(area_name)
          , .predicate=st_intersects
        ) %>% 
        sf::st_transform(crs=plt_crs)
      , aes(color = "Fireshed\nboundary")
      , fill = NA
      , lwd = 1.2
      , linetype = "dashed"
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , mapping = aes(color = "WCS Landscape\nboundary")
      , fill = NA
      # , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) +
    scale_fill_manual(values = c("All-Lands"="firebrick","USFS-Only"="orange3","Not High Risk"="gray88")) +
    scale_color_manual(values = c("gray44","skyblue2", "black")) +
    labs(
      fill = "Fireshed\nHigh-Risk Status"
      , color = "Spatial\nFramework"
      , title = "Spatial Framework and Risk"
      , caption = paste0(
        "High-Risk Fireshed Project Areas: "
        , sum_dta_temp$total_area_acres[1], " acres"
        , " ("
        , sum_dta_temp$total_area_ha[1], " ha"
        , ")"
      )
    ) +
    coord_sf(expand = F) +
    guides(
      color = guide_legend(order = 1, override.aes = list(orientation = "vertical", size = 8, linewidth = 5, fill = NA))
      , fill = guide_legend(order = 2, override.aes = list(orientation = "vertical", size = 8,linewidth = 0, alpha = 1))
    )
  # return
  return(plt)
}
# spatial_frmwrk_map_fn(row_n = 4)
```

```{r raster-data-read-fn}
# function to read raster data
raster_data_read_fn <- function(row_n = 1) {
 # set up name like in file name
  nm_temp <- paste0(
    "*"
    , area_nm_list[row_n] %>% 
      stringr::str_split(pattern = ":", simplify = T) %>% 
      purrr::pluck(2) %>% 
      trimws() %>% 
      stringr::str_replace_all(pattern = " ", replacement = "_")
    , ".tif$"
  )
  # read all raster data files and stack
  files_temp <- list.files("../data/wildfirepriority_WCS202308/images/",pattern = nm_temp,recursive = T) 
  layers_names <- files_temp %>% stringr::word(1,sep = "/")
  rast_list_temp <- files_temp %>%  
    purrr::map(function(x){
      terra::rast(paste0("../data/wildfirepriority_WCS202308/images/",x)) 
    }) %>% 
    # name list objects
    setNames(layers_names) 
  # return
  return(rast_list_temp)
}
rast_list_temp <- NULL
# rast_list_temp <- raster_data_read_fn(row_n = 4)
```

```{r rast2df-fn}
# define function to select, aggregate, filter, and df from raster
rast2df_fn <- function(sc_n = 1, layer_name = "is_treatable", row_n = 1, rast_agg_fact = 2, keep_0_1_all = "all"){
  # find index of layer name
  layer_name_index <- rast_list_temp[[sc_n]] %>% 
    names() %>% 
    purrr::detect_index(function(x) x == layer_name)
  # mask values
  mask_l <- ifelse(keep_0_1_all == "all"
    , terra::values(rast_list_temp[[sc_n]][[layer_name_index]]) %>% unique() %>% min()
    , as.numeric(keep_0_1_all)
  )
  mask_u <- ifelse(keep_0_1_all == "all"
    , terra::values(rast_list_temp[[sc_n]][[layer_name_index]]) %>% unique() %>% max()
    , as.numeric(keep_0_1_all)
  )
  # mask raster, aggregate, to df
  rast_list_temp[[sc_n]][[layer_name_index]] %>% 
    terra::mask(
      rast_list_temp[[sc_n]][[layer_name_index]] %>% 
        terra::clamp(lower = mask_l, upper = mask_u, values = FALSE)
    ) %>%
    terra::mask(
      wf_landscapes %>%
        dplyr::filter(area_name==area_nm_list[row_n]) %>% 
        terra::vect() %>%
        terra::project(terra::crs(rast_list_temp[[sc_n]][[layer_name_index]]))
    ) %>%
    terra::aggregate(fact = rast_agg_fact, fun = "modal") %>%
    terra::as.factor() %>% 
    terra::project(
      wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs) %>% 
        terra::vect() %>%
        terra::crs()
    ) %>% 
    as.data.frame(xy=T) %>% 
    dplyr::rename(f = 3) %>% 
    dplyr::mutate(
      f=factor(f)
      , scenario_lab = paste0("Scenario ", sc_n)
      , layer_name = layer_name
      , area_name = area_nm_list[row_n]
    )
}
```

```{r rast-area-fn}
rast_area_fn <- function(sc_n = 1, layer_name = "is_treatable", row_n = 1){
  # find index of layer name
  layer_name_index <- rast_list_temp[[sc_n]] %>% 
    names() %>% 
    purrr::detect_index(function(x) x == layer_name)
  # df area for caption
  area_df <- rast_list_temp[[sc_n]][[layer_name_index]] %>%
    terra::mask(
      wf_landscapes %>%
        dplyr::filter(area_name==area_nm_list[row_n]) %>%
        terra::vect() %>%
        terra::project(terra::crs(rast_list_temp[[sc_n]][[layer_name_index]]))
    ) %>%
    terra::project(
      wf_landscapes %>%
        dplyr::filter(area_name==area_nm_list[row_n]) %>%
        sf::st_transform(5070) %>% # transform to GEE proj used for calcs
        terra::vect() %>% 
        terra::crs()
    ) %>%
    terra::freq() %>%
    dplyr::as_tibble() %>% 
    dplyr::mutate(
      area_m2 = count * (terra::res(rast_list_temp[[sc_n]][[layer_name_index]]) %>% prod())
      , area_pct = area_m2 / sum(area_m2, na.rm = T)
      # labels
      , area_ha = area_m2/10000
      , area_acres = area_m2/4046.85642
      , area_ha_lab = scales::comma(area_ha, suffix = "k", scale = 1e-3, accuracy = 1)
      , area_acres_lab = scales::comma(area_acres, suffix = "k", scale = 1e-3, accuracy = 1)
      , area_pct_lab = scales::percent(area_pct, accuracy = 1)
      # data str
      , scenario_lab = paste0("Scenario ", sc_n)
      , layer_name = layer_name
      , area_name = area_nm_list[row_n]
    )
  # return
  return(area_df)
}
# rast_area_fn(row_n = 4, layer_name = "is_protected")
```

```{r landcover-map-fn}
# function to plot basemap + forest&shrub
landcover_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # area for caption using data to match reported in publication
  area_temp <- constrained_by_scnro_ls %>% 
    dplyr::filter(scenario_id==1 & area_name == area_nm_list[row_n]) %>% 
    dplyr::mutate(covertype_area_acres=(covertype_area_ha*10000)/4046.85642) %>% 
    dplyr::mutate(
      dplyr::across(
        tidyselect::starts_with("covertype_area_")
        , ~ scales::comma(.x, suffix = "k", scale = 1e-3, accuracy = 1)
      )
    )
  # plot forest and shrub cover
  plt <- plt_basemap +
    geom_tile(
      data = rast2df_fn(
        sc_n = 1
        , layer_name = "is_selected_nlcd"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill=f)
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) + 
    scale_fill_manual(values = c("forestgreen"), na.value = "transparent") +
    labs(
      title = "Forest & Shrub Land Cover"
      , subtitle = "<span><span style='color:forestgreen;'><b>Forest & Shrub</b></span>"
      , caption = paste0(
          "Forest & Shrub: "
          , area_temp$covertype_area_acres[1], " acres"
          , " ("
          , area_temp$covertype_area_ha[1], " ha"
          , ")"
        )
    ) +
    coord_sf(expand = F) +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
    )

  # return
  return(plt)
}
# landcover_map_fn(row_n = 4, rast_agg_fact = 5)
```


```{r protected-map-fn}
# function to plot basemap + protected
protected_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # area_df
  area_df <- rast_area_fn(sc_n = 1, layer_name = "is_protected", row_n = row_n)
  # plot forest and shrub cover
  plt <- plt_basemap +
    geom_tile(
      data = rast2df_fn(
        sc_n = 1
        , layer_name = "is_protected"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill=f)
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) + 
    scale_fill_manual(values = c("#fadb24"), na.value = "transparent") +
    labs(
      title = "Protected & Inventoried Roadless Areas"
      , subtitle = "<span><span style='color:#fadb24;'><b>Protected & IRA</b></span>"
      , caption = paste0(
          "Protected & IRA: "
          , area_df %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
        )
    ) +
    coord_sf(expand = F) +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
    )

  # return
  return(plt)
}
# protected_map_fn(row_n = 4, rast_agg_fact = 6)
```


```{r slopes-map-fn}
# scales::show_col(viridis::plasma(n = 30))
# function to plot basemap + slopes
slopes_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # area_df
  area_df1 <- rast_area_fn(sc_n = 1, layer_name = "is_steep_slopes", row_n = row_n)
  # area_df
  area_df2 <- rast_area_fn(sc_n = 2, layer_name = "is_steep_slopes", row_n = row_n)
  # plot forest and shrub cover
  plt <- plt_basemap +
    # scenario 1 slopes
    geom_tile(
      data = rast2df_fn(
        sc_n = 1
        , layer_name = "is_steep_slopes"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill="40")
      , alpha = 0.8
      , inherit.aes = F
    ) +
  # scenario 2 slopes
    geom_tile(
      data = rast2df_fn(
        sc_n = 2
        , layer_name = "is_steep_slopes"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill="60")
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) + 
    scale_fill_manual(values = c("#febe2a","#f58c46"), na.value = "transparent") +
    labs(
      title = "Steep Slopes"
      , subtitle = "<span><span style='color:#febe2a;'><b>Slopes >40%</b></span> | <span style='color:#f58c46;'><b>Slopes >60%</b></span></span>"
      , caption = paste0(
          "Slopes >40%: "
          , area_df1 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df1 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
        # sc2 slopes
          , "\nSlopes >60%: "
          , area_df2 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df2 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
        )
    ) +
    coord_sf(expand = F) +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
    )

  # return
  return(plt)
}
# slopes_map_fn(row_n = 4, rast_agg_fact = 6)
```


```{r roads-map-fn}
# scales::show_col(viridis::plasma(n = 30))
# function to plot basemap + roads
roads_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # area_df
  area_df1 <- rast_area_fn(sc_n = 1, layer_name = "is_roads_distant", row_n = row_n)
  # area_df
  area_df2 <- rast_area_fn(sc_n = 2, layer_name = "is_roads_distant", row_n = row_n)
  # plot forest and shrub cover
  plt <- plt_basemap +
    # scenario 1 roads
    geom_tile(
      data = rast2df_fn(
        sc_n = 1
        , layer_name = "is_roads_distant"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill="1000")
      , alpha = 0.8
      , inherit.aes = F
    ) +
  # scenario 2 roads
    geom_tile(
      data = rast2df_fn(
        sc_n = 2
        , layer_name = "is_roads_distant"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill="2000")
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) + 
    scale_fill_manual(values = c("#e56a5d","#be3885"), na.value = "transparent") +
    labs(
      title = "Roads Distant"
      , subtitle = "<span><span style='color:#e56a5d;'><b>Roads >1,000ft</b></span> | <span style='color:#be3885;'><b>Roads >2,000ft</b></span></span>"
      , caption = paste0(
          "Roads >1,000ft: "
          , area_df1 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df1 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
          , "\nRoads >2,000ft: "
          , area_df2 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df2 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
        )
    ) +
    coord_sf(expand = F) +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
    )

  # return
  return(plt)
}
# roads_map_fn(row_n = 4, rast_agg_fact = 6)
```

```{r riparian-map-fn}
# scales::show_col(viridis::plasma(n = 30))
# function to plot basemap + riparian
riparian_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # area_df
  area_df1 <- rast_area_fn(sc_n = 1, layer_name = "is_riparian_buffer", row_n = row_n)
  # area_df
  area_df3 <- rast_area_fn(sc_n = 3, layer_name = "is_riparian_buffer", row_n = row_n)
  # plot forest and shrub cover
  plt <- plt_basemap +
    # scenario 1 riparian
    geom_tile(
      data = rast2df_fn(
        sc_n = 1
        , layer_name = "is_riparian_buffer"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill="ft100")
      , alpha = 0.8
      , inherit.aes = F
    ) +
  # scenario 3 riparian
    geom_tile(
      data = rast2df_fn(
        sc_n = 3
        , layer_name = "is_riparian_buffer"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill="ft50")
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) + 
    scale_fill_manual(values = c("#a01a9c","#6e00a8"), na.value = "transparent") +
    labs(
      title = "Riparian Buffer"
      , subtitle = "<span><span style='color:#a01a9c;'><b>Riparian Buffer 100ft</b></span> | <span style='color:#6e00a8;'><b>Riparian Buffer 50ft</b></span></span>"
      , caption = paste0(
          "Riparian Buffer 100ft: "
          , area_df1 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df1 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
          , "\nRiparian Buffer 50ft: "
          , area_df3 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df3 %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
        )
    ) +
    coord_sf(expand = F) +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
    )

  # return
  return(plt)
}
# riparian_map_fn(row_n = 4, rast_agg_fact = 6)
######## export image
# ggplot2::ggsave(
#     filename = paste0("../data/xxx_riparian_fact2.png")
#     , plot = ggplot2::last_plot()
#     , width = 11
#     , height = 8.5
#     , units = "in"
#     , dpi = "print"
#     , bg = "white"
#   )
```


```{r administrative-map-fn}
# function to plot basemap + administrative
administrative_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # area_df
  area_df <- rast_area_fn(sc_n = 1, layer_name = "is_administrative", row_n = row_n)
  # plot forest and shrub cover
  plt <- plt_basemap +
    geom_tile(
      data = rast2df_fn(
        sc_n = 1
        , layer_name = "is_administrative"
        , row_n = row_n
        , rast_agg_fact = rast_agg_fact
        , keep_0_1_all = "1"
      )
      , mapping = aes(x=x,y=y,fill=f)
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) + 
    scale_fill_manual(values = c("#47039F"), na.value = "transparent") +
    labs(
      title = "Administratively Designated Areas"
      , subtitle = "<span><span style='color:#47039F;'><b>Administrative Designation</b></span>"
      , caption = paste0(
          "Administratively Designated: "
          , area_df %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_acres_lab)
          , " acres"
          , " ("
          , area_df %>% 
            dplyr::filter(value == 1) %>% 
            dplyr::pull(area_ha_lab)
          , " ha"
          , ")"
        )
    ) +
    coord_sf(expand = F) +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
    )

  # return
  return(plt)
}
# administrative_map_fn(row_n = 4, rast_agg_fact = 6)
```


```{r treatable-map-fn}
# function to plot basemap + treatable
treatable_map_fn <- function(row_n = 1, rast_agg_fact = 2) {
  # plot available/constrained
  plt <- plt_basemap +
    geom_tile(
      data = 1:length(rast_list_temp) %>% 
        purrr::map(
          rast2df_fn
          , layer_name = "is_treatable"
          , row_n = row_n
          , rast_agg_fact = rast_agg_fact
          , keep_0_1_all = "all"
        ) %>% 
        dplyr::bind_rows()
      , mapping = aes(x=x,y=y,fill=f)
      , alpha = 0.7
      , inherit.aes = F
    ) +
    geom_sf(
      data = wf_landscapes %>% 
        dplyr::filter(
            area_name == area_nm_list[row_n]
          ) %>% 
        sf::st_transform(crs=plt_crs)
      , fill = NA
      , color = "black"
      , lwd = 0.6
      , inherit.aes = F
    ) +
    geom_text(
      data = constrained_by_scnro_ls %>% 
        dplyr::filter(area_name==area_nm_list[row_n]) %>% 
        dplyr::mutate(area_pct_lab = scales::percent(pct_rmn5_administrative, accuracy=1))
      , mapping = aes(
        label = paste0(
            "Mechanically available: "
            , area_pct_lab
            # , " ("
            # , area_acres_lab
            # , " acres; "
            # , area_ha_lab
            # , " ha"
            # , ")"
          )
        , x = ggplot2::layer_scales(plt_basemap)$x$range$range[1]
        , y = ggplot2::layer_scales(plt_basemap)$y$range$range[1]
        , hjust = 0
        , vjust = 1.1
      )
      , inherit.aes = F
      , size = 4
    ) +
    facet_grid(
      cols = vars(scenario_lab)
      , labeller = label_wrap_gen(width = 35, multi_line = TRUE)
      # , switch = "both"
    ) +
    scale_fill_manual(values = c("#7A0403","#466BE3"), na.value = "transparent") +
    labs(
      title = "Mechanical Operability"
      , subtitle = "<span><span style='color:#466BE3;'><b>Available</b></span> | <span style='color:#7A0403;'><b>Constrained</b></span></span>"
    ) +
    coord_sf(expand = F, clip = "off") +
    theme(
      legend.position = "none"
      , plot.subtitle = ggtext::element_markdown(size = 10)
      , strip.text = element_text(color = "black", face = "bold")
    )

  # return
  return(plt)
}
# treatable_map_fn(row_n = 4, rast_agg_fact = 7)
# ######## export image
# ggplot2::ggsave(
#     filename = paste0("../data/xxx_istreatable.png")
#     , plot = ggplot2::last_plot()
#     , width = 11
#     , height = 8.5
#     , units = "in"
#     , dpi = "print"
#     , bg = "white"
#   )
```


```{r reduction-table-fn}
reduction_table_fn <- function(row_n = 1) {
  table_temp <- 
    constrained_by_scnro_ls %>% 
      dplyr::filter(area_name == area_nm_list[row_n]) %>%
      dplyr::mutate(
        dplyr::across(
          tidyselect::ends_with("_ha")
          , ~ scales::comma(.x, suffix = "k", scale = 1e-3, accuracy = 1)
        )
        , dplyr::across(
          tidyselect::starts_with("pct_")
          , ~ scales::percent(.x, accuracy = .1)
        )
      ) %>% 
      dplyr::select(
        # area_name
        scenario_lab
        , covertype_area_ha
        , pct_covertype_area
        , pct_rdctn1_protected
        , pct_rdctn2_slope
        , pct_rdctn3_roads
        , pct_rdctn4_riparian
        , pct_rdctn5_administrative
        , rmn5_administrative_area_ha
        , pct_rmn5_administrative
      ) %>% 
      dplyr::arrange(desc(scenario_lab)) %>% 
      dplyr::rename(
        "Scenario\n " = scenario_lab
        , "Forest & Shrub\n(ha)" = covertype_area_ha
        , "Forest & Shrub\n(%)" = pct_covertype_area
        , "Protected\n& IRA " = pct_rdctn1_protected
        , "Slope\nSteepness" = pct_rdctn2_slope
        , "Road\nDistance" = pct_rdctn3_roads
        , "Riparian\nBuffer" = pct_rdctn4_riparian
        , "Administrative\n " = pct_rdctn5_administrative
        , "Mechanically\nAvailable (ha)" = rmn5_administrative_area_ha
        , "Mechanically\nAvailable (%)" = pct_rmn5_administrative
      )
  # table theme
  ttheme_temp <- ggpubr::ttheme(
    base_style = "light"
    , colnames.style = colnames_style(
      size = 9
      , face = "bold"
      , fill = "white"
      , linewidth = 0
      , linecolor = "transparent"
    )
    , tbody.style = tbody_style(
      size = 8
      , fill = c("white", "gray96")
      , linewidth = 0
      , linecolor = "transparent"
    )
  )
  # plot table
  plt <- ggpubr::ggtexttable(table_temp, rows = NULL, theme = ttheme_temp) %>% 
    ggpubr::tab_add_footnote(
        text = paste0(
          "Combined forest and shrubland area within the landscape boundaries"
          , " and the percent reduction of different types of constraints"
          , "        "
          , "\non mechanical treatment based on the three scenarios of "
          , " operational constraints considered in this analysis."
          , "                                         "
        )
        , size = 9
        , just = "right"
        , padding = unit(0.7, "line")
        , hjust = 1.08
      )
  return(plt)
}
```


```{r}
# plot for titler
title_plot_fn <- function(row_n = 1) {
  plt <-
    ggplot() +
    labs(
      title = wf_landscapes %>% dplyr::filter(area_name==area_nm_list[row_n]) %>% dplyr::pull(name)
      , subtitle = paste0(
        wf_landscapes %>% dplyr::filter(area_name==area_nm_list[row_n]) %>% dplyr::pull(state)
        , " ("
        , wf_landscapes %>% dplyr::filter(area_name==area_nm_list[row_n]) %>% dplyr::pull(investment)
        , " investment)"
        , "\n"
        , wf_landscapes %>% dplyr::filter(area_name==area_nm_list[row_n]) %>% dplyr::pull(acres) %>% scales::comma(suffix = "k", scale = 1e-3, accuracy = 1)
        , " acres ("
        , wf_landscapes %>% dplyr::filter(area_name==area_nm_list[row_n]) %>% dplyr::pull(hectares) %>% scales::comma(suffix = "k", scale = 1e-3, accuracy = 1)
        , " ha)"
      )
      # , caption = "none"
    ) +
    theme_void() +
    theme(
      panel.background = element_blank()
      , plot.title = element_text(face = "bold", size = 44)
      , plot.subtitle = element_text(size = 18)
    )
  # return
  return(plt)
}
# title_plot_fn(4)
```



```{r landscape-map}
xxx <- 4
# set basemap
plt_basemap <- landscape_basemap_fn(row_n = xxx)
# load raster data
rast_list_temp <- raster_data_read_fn(row_n = xxx)
# get all the plots
# ls()[grep("_fn",ls())]
spatial_frmwrk_map_temp <- spatial_frmwrk_map_fn(row_n = xxx) + 
  theme(
    legend.position = "top"
    , legend.direction = "vertical"
    , plot.title = element_blank()
  )
landcover_map_temp <- landcover_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
protected_map_temp <- protected_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
slopes_map_temp <- slopes_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
roads_map_temp <- roads_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
riparian_map_temp <- riparian_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
administrative_map_temp <- administrative_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
treatable_map_temp <- treatable_map_fn(row_n = xxx, rast_agg_fact = 8) +
  theme(plot.title = element_blank())
reduction_table_temp <- reduction_table_fn(row_n = xxx)
title_plot_temp <- title_plot_fn(row_n = xxx)
```

    
Row
-------------------------------------
    
### Chart 1
    
```{r, include = T}
landcover_map_temp
```
 
### Chart 2
    
```{r, include = T}
protected_map_temp
``` 

### Chart 3

```{r, include = T}
slopes_map_temp
```

Row
-------------------------------------
    
### Chart 4
    
```{r, include = T}
roads_map_temp
```
    
### Chart 5

```{r, include = T}
riparian_map_temp
```

### Chart 6

```{r, include = T}
administrative_map_temp
```
