--- 
title: "WCS Mechanical Constraints"
author: "George Woolsey"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    includes:
      in_header: header.html
documentclass: book
book_filename: "wcs_mechanical_constraints"
output_dir: "../docs"
language:
  ui:
    chapter_name: "Section "
delete_merged_file: true
bibliography: [packages.bib]
biblio-style: apalike
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
suppress-bibliography: false
lang: en-US
zotero: true
link-citations: true
description: "Using the bookdown package to write a book of data exploration. The output format for this example is bookdown::gitbook."
---

# Caution

This is a sandbox. Do not trust or re-use anything on here because it is a sandbox.

# Objective

A complex web of regulations and other constraints limit the extent and intensity of forest treatment application (Van Deusen et al., 2012; North et al., 2015; Lydersen et al., 2019). Physical-environment, socioeconomic, and regulatory factors alone or in combination affect what type of treatment is practical or allowed in different areas. 

The objective of this study is to spatially identify the treatable area and the constraints on management activities in western USFS managed forests and the 21 priority landscapes outlined in the USFS Wildfire Crisis Strategy (USFS). Specific questions asked in this analysis are: i) What is the spatial extent on which management is constrained? ii) Which constraining factor(s) — physical-environment, socioeconomic, regulatory — is most limiting to forest management?

# Data Sources

The data utilized for this analysis was generated in Google Earth Engine using [this script](https://code.earthengine.google.com/bc974ce5d2f8a25a2eb75af5766395b9?noload=true). This program outputs 1) a data table of features - USDA Forest Service (USFS) managed forests - with user-defined constraints to forest managment and the reduction in treatable forested area based on those constraints, and 2) a shapefile of the spatial arrangement of treatable and constrained forested area within the boundary of each feature.

The data products used in this study include:

1) The [National Land Cover Database (NLCD)](https://www.usgs.gov/centers/eros/science/national-land-cover-database) was used to define forested area based on 2019 classification at 30m.
2) The [PAD-US](https://www.usgs.gov/programs/gap-analysis-project/science/pad-us-data-overview) product was used to identify protected areas that are dedicated to the preservation of biological diversity and to other natural, recreation and cultural uses, managed for these purposes through legal or other effective means.
3) The [USGS 3DEP](https://www.usgs.gov/3d-elevation-program/about-3dep-products-services) Seamless National Map (10m) was used to determine slope.
4) The [USFWS Threatened & Endangered Species Active Critical Habitat Report](https://ecos.fws.gov/ecp/report/table/critical-habitat.html) was used to determin the proposed and final critical habitat for species listed as Threatened and Endangered by the FWS, or that are jointly managed by FWS/NMFS.
5) The [National Hydrography Dataset (NHD)](https://www.usgs.gov/national-hydrography/national-hydrography-dataset) was used to define the United States water drainage network made up of stream features and waterbody polygons.
6) Road and Trail networks were determined utilizing:
    i.  The United States Census Bureau [TIGER dataset](https://www.census.gov/programs-surveys/geography/guidance/tiger-data-products-guide.html) (2016 release)
    ii. The [USFS FACTS database](https://data.fs.usda.gov/geodata/edw/datasets.php?xmlKeyword) products: [Motor Vehicle Use Map: Roads](https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Road_MVUM.xml); [Motor Vehicle Use Map: Trails](https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Trail_MVUM.xml); [National Forest System Roads](https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RoadCore_FS.xml); [National Forest System Trails](https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.TrailNFS_Publish.xml)

# Treatable Area Scenario

Constraint levels from least flexible to most flexible in interpretation and implementation:

0) Forested - forested area based on NLCD (2019) classification at 30m
1) Protected - GAP Status 1 and inventoried roadless areas (IRA)
2) Slope > 35% - based on DEM at 10m
3) Distance from Road > 2000ft - based on road and trail data layers
4) Riparian Buffer - buffer of 100 ft. on streams and waterbodies based on NHD water network
5) Administrative - USFWS sensitive species habitat and GAP Status 2
    

```{r include=FALSE, echo=FALSE}
knitr::write_bib(c(
  .packages(),
  'bookdown'
  , 'knitr'
  , 'rmarkdown'
  , 'tidyverse'
  , 'lubridate'
  , 'scales'
  , 'ggrepel'
  , 'viridis'
  , 'kableExtra'
  , 'sf'
  , 'stars'
  , 'lwgeom'
  , 'mapview'
  , 'leafpop'
  , 'cowplot'
  , 'RColorBrewer'
  , 'USAboundaries'
  , 'nhdplusTools'
), 'packages.bib')
```
